// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bedznnnkawwqzfrypxnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZHpubm5rYXd3cXpmcnlweG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDA0MjksImV4cCI6MjA2NzExNjQyOX0.EPuSe0Nd1NktXwfroLppjh_9HZnSMHAguY8F8akVywQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});